[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "python-mock-hooks"
version = "0.2.0"
description = "A pre-commit hook restricting monkeypatch methods and unittest.mock"
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"
dependencies = ["ast-grep-cli==0.45.2"]

[project.scripts]
python-mock-hooks = "python_mock_hooks:main"
tests-without-ifs = "python_mock_hooks:tests_without_ifs"

[tool.hatch.build.targets.wheel]
packages = ["src/python_mock_hooks"]

[dependency-groups]
dev = ["pytest", "pre-commit", "prek", "pyrefly"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pyrefly]
project-includes = ["src", "tests"]
